lgi-devs/lgi

lgi/init.lua
Don't attempt to direclty access globals that might not
exist, instead use rawget().
Strict Mode:
http://metalua.luaforge.net/src/lib/strict.lua.html
=> Support running LGI in strict mode

lgi/Makefile, lgi/core.c
On Mac OS X, the `file_name` parameter of `g_module_open()` must be an
abosolute path to open the module successfully.
To fulfil the requirement, the following changes were done:
* `lgi/Makefile`
- Add a new variable called `GOBJECT_INTROSPECTION_LIBDIR` whose value
is set by `pkgconfig` automatically.
- Pass the value of the variable to the compiler as a CPP constant
macro via `CFLAGS`.
* `lgi/core.c`
- Construct the absolute path of a module using the value of
`GOBJECT_INTROSPECTION_LIBDIR`.
=> Tweaks for the build on Mac OS X

lgi/record.lua
libgtop (available at https://github.com/GNOME/libgtop/commits/master) has a
struct glibtop_cpu. While trying to load this through e.g.
require("lgi").GTop.glibtop_cpu, the following error occurred:
lgi/record.lua:153: attempt to index a nil value (field 'return_type')
This occurred because the code tried to find a constructor for this struct and
for this it "un-camel-cased" the struct name, which didn't change anything,
because the struct name isn't camel-cased, and then assumed that the result were
information about a function. However, this just found the struct again.
Fix this by explicitly testing if the type of the result is a function.
Signed-off-by: Uli Schlachter <uli.schlachter@informatik.uni-oldenburg.de>
(No unit test because I don't know how and if this is wrong/stupid, feel …
=> record.load: Require constructor to be a function

lgi/marshal.c, tests/gio.lua, tests/test.lua
The C-API will return a NULL-pointer when the end of the input is reached. However, `lua_pushstring` and `lua_pushlstring` turn NULL-pointers into empty strings and so end-of-file became indistinguishable from an empty line in Lua. Fix this by marshalling a NULL "string" pointer (actually: UINT8 array) as `nil`.
This fixes https://github.com/pavouk/lgi/issues/125.
Feel free to replace this with a better fix or tell me what I did wrong.
=> Make it possible to detect EOF on a GDataInputstream

lgi/Makefile
version.lua is specified twice during the copy: one in VERSION_FILE and
one in CORESOURCES (make uses lazy evaluation so CORESOURCES is expanded
only when used, i.e. during the copy).
=> Do not copy version.lua twice

lgi/Makefile
eb1b930892da75135a1af6e377a3ebe27db76b85 already introduced a PKG_CONFIG variable, so use it instead of hard-coding "pkg-config".
=> Don't hard-code the pkg-config executable

lgi/override/Gio-DBus.lua, tests/Makefile, tests/dbus.lua
I think that this should fix #88, but I'm not completely sure. Feel free to cherry-pick only parts of this (e.g. if you don't like the unit test). Also, feel free to tell me what needs to be changed. :-)
@Elv13 Could you check if this fixes the crashes that you saw with wirefu?
Edit: Important point: I only tested this with Lua 5.3. This might be important for the first commit. Should I try setting up travis-ci.org for lgi and writing a `.travis.yml` as a separate pull request?
=> Fix crash due to Gio.DBusProxy.get_interface_info

lgi/core.c
https://developer.gnome.org/glib/stable/glib-Message-Logging.html#id-1.4.12.6.8
This allows writing to the journal and in the future opens up possibilities for exposing more information.
=> Use structured logging when available

.travis.yml
The unofficial GitHub mirror became a bit more official and
removed/changed releases. Switch to the official Lua site instead.
The Travis build for #152 failed. This fixes things (hopefully).
=> .travis.yml: Fix Lua download link

README.md
In the [changelog for 0.9.1](https://github.com/pavouk/lgi#091-27-may-2016) full Lua 5.3 compatibility is stated so I took the liberty of adding this to the README.
=> Add Lua 5.3 compatibility to README

samples/GDbus/list-system-services.lua
Caught this while trying to tame lgi.
=> DBusCallFlags are needed in method calls

lgi/callable.c, lgi/core.c, lgi/gi.c, lgi/object.c, lgi/record.c
Fixes: https://github.com/pavouk/lgi/issues/122
Signed-off-by: Uli Schlachter <uli.schlachter@informatik.uni-oldenburg.de>
I tried to come up with a test case for this, but failed. So far I only managed to make valgrind complain about a use-after-free, but I haven't actually managed to cause a crash (and even less: reproducably so).
=> Make objects unusable in the __gc metamethod

lgi/namespace.lua, lgi/override/Gtk.lua
When loading a namespace, namespace.require() also loads the suitable
override file. When no override file exists, this should be non-fatal,
so pcall(require, override_name) is used. However, any other errors
besides "no such file" should still be fatal. Thus, in this case
namespace.require() require()s the override file again expecting it to
fail in the same way again, but this time the error is propagated out.
This behaviour causes problems for Gtk when gtk_init_check() fails.
Since gtk was already (unsuccessfully) initialized when the override
file was loaded the first time, the call to gtk_disable_setlocale() that
is done first results in a warning "gtk_disable_setlocale() must be
called before gtk_init()" to be printed by Gtk. Also, the actual error
message will be "assertion …
=> Better error message when Gtk.init_check() fails

.travis.yml
This is WIP since I am quite sure that this new check fails. `make install` only picks the right installation dir for Lua 5.1, I bet.
I will remove the WIP from the title once this is done and works
=> Traivs: Check that lgi works after 'make install'

lgi/override/GObject-Object.lua
Previously, g_object_newv() was annotated with [rename-to g_object_new].
This annotation was moved to (the new function)
g_object_new_with_properties(). Since this expects different arguments,
things break. Work around this by using g_object_newv() directly if it
exists.
Fixes: https://github.com/pavouk/lgi/issues/167
@TingPing Please test this with a newer GLib which would be broken without this patch.
=> Work around API break in GLib 2.54

.travis.yml, tests/Makefile, tests/dbus.lua, tests/gio.lua
This makes tests/Makefile run the tests under "dbus-run-session" so that
a DBus user session surely exists. Thus, the code using Gio.TestDBus is
no longer necessary and can be removed.
=> Run tests in a proper DBus session

lgi/callable.c
According to [1], return values smaller than sizeof(long) are returned
as ffi_arg or ffi_sarg. Thus, the code here needs to use ffi_sarg
instead of int to work correctly.
This fixes a test failure on s390x that boils down to
cairo_pattern_get_type() returning 2, but the C code here turns that
into a value of 0.
A big "thank" you to Debian and specifically to Mattia Rizzolo for
giving me access to a porterbox so that I could debug this myself.
[1]: https://linux.die.net/man/3/ffi_call
=> callable: Fix enum return from C functions

tests/glib.lua
tests/glib.lua counts to one million in an attempt to spend some time so
that it can test that GLib's Timer correctly nootices that some
timepassed. The "count to one million"-loop needs about three
milliseconds here with Lua 5.2. LuaJIT is likely faster than this.
Instead of relying on this loop being slow enough, replace it with a
call to g_usleep to sleep for a millisecond.
=> Replace busy loop with usleep call

lgi/override/cairo.lua
Doing core.module('cairo', 2) results in dlopen("libcairo.so.2"). This
causes a problem in NixOS since there is no single, global library
search path and instead absolute paths to libraries are inserted during
build. Thus, loading the library fails.
However, in NixOS the cairo-1.0.typelib is patched to contain a full
path to libcairo.so.2. Thus, when causing this library to be loaded
through gobject-introspection, everything works out.
To achieve this goal, this commit reorders some code in the cairo
override file so that first some enums are loaded through
gobject-introspection (causing libcairo.so to be loaded) and only
afterwards cairo is opened directly (which does not need a search path
since cairo was already loaded before).
Related to: https://github.com/NixOS/nixpkgs/pull/34584 …
=> cairo: Use the typelib before loading cairo directly

lgi/callable.c, tests/gio.lua
Sorry for the spam, but here is a new attempt following up on #181 and #183. This time I first did some refactoring to keep "the actual change" small. Now, errors during marshalling are still thrown on the original thread/coroutine when possible.
=> Use marshalling thread2

lgi/meson.build, lgi/version.lua.in, meson.build, meson_options.txt, tests/meson.build
This is very useful on Windows and it matches the rest of the stack such as `gobject-introspection` and `glib` which are moving to meson.
=> Add meson build system support

docs/gtk.md, lgi/override/Gtk.lua
This patch enables indexing Gtk.TreeStore and Gtk.ListStore with numbers (e. g. `liststore[0]`) or strings (e.g. `treestore["1:2"]`). Usefull example: you got string from GtkComboBox, and want to give value from its ListStore, then it will be so easy:
local active = MyComboBox:get_active()
local row = MyListStore[active]
Should I provide tests for this feature?
=> Add support for indexing Gtk.TreeStore and Gtk.ListStore with nums or strs

docs/variant.md
This edit adds description of a `get_child_value` method call. This may be helpful for people, trying to work with DBus.
=> variant documentation access complex data types

lgi/override/cairo.lua, tests/cairo.lua
Some cairo types are reference-counted and provide their own custom
reference-counting. Hook up lgi's refsink mechanism to cairo's custom
reference functions, if the type has it.
https://github.com/pavouk/lgi/issues/210
=> refsink cairo refcounted types

meson.build, tests/meson.build
There was a hack where some extra arguments are passed to the test
runner by meson. This hack was necessary so that some dependencies are
generated before the test itself was started. However, these arguments
were interpreted as a list of subtests to run and so no tests were
actually run.
Fix this by explicitly specifying these targets as dependencies. This is
possible in newer versions of meson, hence the required meson version
gets bumped.
Fixes: https://github.com/pavouk/lgi/issues/214
CC @TingPing
=> meson: Run tests correctly

tests/test.lua
Apparently, Lua ignores the return value of the main chunk. To make this
fail explicitly, this now calls io.exit() instead.
Note that this exposes a bug in the meson build, which now fails.
=> tests/test.lua: Use os.exit() instead of return

tests/gobject.lua
The subclass test caused the following warning:
(lua5.2:14980): GLib-GObject-CRITICAL **: 13:02:03.551: Object class
LgiTestFakeMonitor1 doesn't implement property 'network-metered' from
interface 'GNetworkMonitor'
This new property was added in Gio 2.46. The fix here is to implement
that property. That should not cause problems with older versions of
Gio, because there the extra property would just be ignored.
=> Fix GObject warning in tests

lgi/override/GLib-Variant.lua, tests/variant.lua
This all started with me noticing that when transforming a bytestring to
Lua, the resulting string was truncated at the first null byte. I added
a new test variant.bytestring_embedded_null() (see diff) and started
trying to fix this test.
The fix is simple: Instead of using g_variant_get_bytestring() (which
only providers a pointer to the beginning of the data, but no length) to
transform the value to Lua, the code has to use the already existing
.data property. This code carefully gets the length of the bytestring
and creates a bytes object of appropriate length. Easy fix. This is
where the rabbit hole started.
The docs for g_variant_new_bytestring() say:
The nul terminator character at the end of the string is stored in the
array.
Thus, all existing code that creates a GVariant of type …
=> Fix bytestring handling with embedded null bytes

lgi/override/Gtk.lua, tests/gtk.lua
Turned out that my #161 may lead to crashes under some conditions. This patch fixes that. For example, I got crash in `samples/gtk-demo/main.lua:102`.
Note: gtk warning still gets printed to console. I'm not really sure how much of a bug is this, but still better avoid crashing.
=> Fail gracefully on bad TreePath

lgi/buffer.c, lgi/callable.c, lgi/core.c, lgi/gi.c, lgi/lgi.h, lgi/marshal.c, lgi/object.c, lgi/record.c, tests/gireg.lua
This patch utilizes Lua functions for integers, making them appear the right way on Lua 5.3.
I've tested this on a few of configurations (all use XUbuntu 18.04):
* 64-bit, Lua 5.3
* 64-bit, Lua 5.2
* 64-bit, Lua 5.1
* 32-bit, Lua 5.3
* 32-bit, Lua 5.1 (added)
There are few tings to remember:
* This changes behavior on Lua 5.3 for numbers which don't have integer representation: they now cause error instead of silently rounding towards zero. Sounds reasonable for me.
* GCC show warning about int-to-pointer conversion on Lua 5.3 32-bit platform. Doesn't sound significant to me anyways as everything works.
<s>I probably should test on Lua 5.1 32-bit as well, will report results soon.</s> Done, it works.
=> Use integers in Lua 5.3

samples/tcpsrv.lua, samples/udpsrv.lua
Add TCP and UDP server samples.
See #235 for details.
=> add TCP and UDP server samples

lgi/Makefile, tests/Makefile
With this change, CPPFLAGS set by the build system are honoured.
=> Honour CPPFLAGS during build

README.md, lgi/callable.c
This is the part of #199 that makes the build against Lua 5.4 pass. However, Lua 5.4 is not added to Travis since it does not pass the test suite. Thus, this is only experimental support.
Let's hope that someone magically shows up and figures out what the problem is...
=> Add experimental support for Lua 5.4

lgi/override/Gdk.lua, lgi/override/Gtk.lua, tests/gobject.lua, tests/gtk.lua
CC @TingPing Could you take a look at this?
This PR basically hides code behind `if`s until `make check` stops erroring out when Gtk4 GIR is installed.
Fixes: #226
=> Do not error out with Gtk4

lgi/core.c, meson.build, tests/meson.build
Hi,
This attempts to add support to the Meson build files to build with Visual Studio, by:
*  Avoiding configuration errors since Lua may have been found via CMake on Visual Studio-like builds instead of pkg-config by only trying to retrieve Lua pkg-config variables if it is really found via pkg-config.
* Force-include `msvc_recommended_pragmas.h` on Visual Studio builds, so that we can silence compiler warnings that we really don't need to bother about and make the ones that we should really worry about glaring to us.
* Don't prefix DLL names with `lib` in `core.c` for Visual Studio-like builds, since the Meson build files for Cairo do not prepend such prefixes, which is where this comes to play.
* Fix building `regress.dll` by making sure symbols are exported, so that its introspection …
=> Meson: Support Visual Studio builds

meson.build
Without this, I get the following warnings:
```
WARNING: Project specifies a minimum meson_version '>= 0.46.0' but uses features which were added in newer versions:
* 0.49.0: {'compiler.get_argument_syntax_method'}
* 0.50.0: {'install arg in configure_file'}
```
=> Require meson 0.50.0

lgi/marshal.c
g_memdup() should be avoided if possible:
https://nvd.nist.gov/vuln/detail/CVE-2021-27219
=> Use g_memdup2 if available

lgi/callable.c, tests/progress.lua, tests/test.lua
This touches a quite delicate part of LGI, so it probably requires much more eyeballs than only mine.
=> Progress callback

samples/console.lua, samples/goocanvas.lua, samples/gstvideo.lua, samples/gtk-demo/main.lua, samples/gtkhello.lua
This is needed for systems that support both GTK 3 and GTK 4, otherwise,
'require' may try to pull in GTK 4, or other mutually incompatible
library versions.
=> Specify more library versions in sample code

lgi/Makefile, tests/Makefile
in nixpkgs we set the PKG_CONFIG env var to the correct pkg-config and
i was getting 'pkg-config: No such file or directory'
https://makefiletutorial.com/
=> Makefiles: do not override PKG_CONFIG variable if it is set

lgi-scm-1.rockspec
This adds a rockspec that can build from the master branch of the source repository. In this convention we check this rockspec in because it can be used universally. Generally versioned rockspecs you don't check in.
This will enable someone to build and install the latest version via LuaRocks with a command like:
```
luarocks install https://raw.githubusercontent.com/lgi-devs/lgi/master/lgi-scm-1.rockspec
```
After this change is accepted, we can also upload the scm rockspec to luarocks.org so we can use the "dev" manifest to also install the development version of this module
=> add an scm rockspec

lgi/override/Gtk.lua
Running the following code should result in a window with a button with a box, but only the window shows.
<details><summary><b><i>Snippet: GTK4 window with a Box</i></b></summary>
<p>
```
lgi = require 'lgi'
gtk = lgi.require('Gtk','4.0')
local app= gtk.Application{application_id = 'org.phicross.gtk4lua.intro'}
local handles = {application = app}
function app:on_startup()
end
function app:on_activate()
handles.window = gtk.ApplicationWindow{ id = 'daWindow',
application = self,
title = "intro app.",
default_width = 200,
default_height = 200
}
handles.atop = gtk.Box{ orientation = gtk.Orientation.VERTICAL,
id='daBox',
gtk.Button {
id = 'daButton',
label = 'slap',
on_clicked = function(self)
print 'did you just slap me?'
end
} 
}
handles.window:set_child(handles.atop)
print 'app ready.' …
```
=> Fix Box hierarchy for GTK4

lgi-scm-1.rockspec, rockspec.in
Having installed `lgi` through luarocks in a MinGW 64-bit console and used it for various demos successfully I suggest to add `mingw` to the list of supported platforms in the rockspec, so Windows users can install the `lgi` rock without any modifications to the repo through luarocks.
When testing the various demos in `gtk-demo` all appeared to work except of the Images and Rotated Button demos. I have also tested some Xournal++ demos that use `lgi` and they worked too. 
Some more infos on how to install can be found in [this discussion](https://github.com/xournalpp/xournalpp/discussions/4522#discussioncomment-8789465). Note that for running `gtk-demo` you also have to install [`gtksourceview3`](https://packages.msys2.org/package/mingw-w64-x86_64-gtksourceview3?repo=mingw64).
=> Add mingw to supported platforms

lgi/class.lua, lgi/ffi.lua
Fixes #71
Calling gi.require may not always succeed. If we do not wrap it in an `assert`, we will get confusing error messages.
For example, a failure in `lgi/ffi.lua` would look like:
attempt to index local 'gobject' (a boolean value)
wrapping `gi.require` with `assert` instead would show a more informative message:
Typelib file for namespace 'win32', version '1.0' not found
This change updates both `lgi/class.lua` and `lgi/ffi.lua` which appear to be the only two files in the codebase that do not wrap `gi.require` with an `assert`.
A practical example where this would have been useful is https://github.com/NixOS/nixpkgs/issues/139159#issuecomment-2156172046
I actually managed to figure out the issue with NixOS using this patch.
Thanks for developing and maintaining lgi!
=> Wrap gi.require with assert in class.lua and ffi.lua

.github/test-for-msvc-ci.lua, .github/workflows/msvc-ci.yml
I have added a GitHub workflow to build, install and test LGI on Lua (PUC) for both GTK 3 and GTK 4 on MSVC toolchain.
On Windows, it is needed to quickly detect changes in the code that break the build for MSVC toolchain.
* To install GTK, I used prebuilt (MSVC) binaries of GTK 3 and GTK 4 provided by [wingtk](https://github.com/wingtk/gvsbuild), which is a well known project to deliver GTK on Windows. They are even cited on GTK's webpage at the moment.
* To install Lua (PUC), I used a project [LuaInstaller](https://github.com/luau-project/LuaInstaller) that I am maintaining for quite a long time. Recently, I did update the tool in order to emit a ```pkg-config``` file for Lua (luaXY.pc) to ease LGI installation.
**P.S.**: In the latest release of LuaInstaller, the build of LGI is even …
=> ci: MSVC on Windows

.github/workflows/ci.yml, .github/workflows/msvc-ci.yml
* Fixed LuaJIT build on Ubuntu's CI: now, source code is fetched from the GitHub mirror. Quoting from [https://luajit.org/download.html](https://luajit.org/download.html)
> LuaJIT is only made available as source code from a git repository.
> LuaJIT uses rolling releases. There are no release tarballs available for download.
* Updated the latest Lua (PUC) version from 5.4.3 to 5.4.7;
* LuaInstaller was updated from v0.2.0.0 to v0.3.0.0, which addressed a potential bug that could happen in the future (you can read details at [v0.3.0.0 release](https://github.com/luau-project/LuaInstaller/releases/tag/v0.3.0.0)).
=> fix: LuaJIT on Ubuntu CI

.github/workflows/ci.yml, .github/workflows/msvc-ci.yml
Recently, GitHub updated their Ubuntu runners labeled as ```ubuntu-latest``` to run under Ubuntu 24.04.
> [!NOTE]
> 
> Previously, ```ubuntu-latest``` ran on Ubuntu 22.04.
Due this change, the package ```libreadline-dev``` is not installed anymore by default, causing the current (Ubuntu) CI to fail while building Lua even for unrelated changes (notably [https://github.com/lgi-devs/lgi/pull/331](https://github.com/lgi-devs/lgi/pull/331)), because ```readline``` is missing in the system.
* Added a step to install ```libreadline-dev``` before the build of Lua on (Ubuntu) CI;
* Minor edits in the (Ubuntu) CI regarding the ```LUA_VERSION``` environment variable;
* Updated MSVC CI to use the latest LuaInstaller version to install Lua ([Release …
=> fix: install libreadline-dev on CI

lgi/core.c
~This still needs some testing. Don't merge yet.~
This has been tested on MacOS Intel (on an old MacBook Pro) and on Macos ARM (M2 mini) through an automatic build of Xournal++ that bundles `lua-lgi`, see https://github.com/xournalpp/xournalpp/pull/6161/files, using GLib 2.82.
On MacOS ARM I have tested all gtk-demo examples after modifying `main.lua` such that it can be run as Xournal++ plugin. I had to replace the GtkSource.View by a Gtk.TextView, since we don't have GtkSourceView bundled in the right version for Xournal++. All gtk-demos worked except the Images demo, which crashes after a short while. It's the same on Windows and Linux. The UI-manager demo asks to press the Alt key, which is a bit unfortunate on MacOS. 
This PR basically reverts …
=> Fix core_module on MacOS for GLIB >= 2.76
